"""remove color from priority levels

Revision ID: 94cac90c7580
Revises: 87fd24734672
Create Date: 2025-12-24 10:02:09.349389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cac90c7580'
down_revision: Union[str, Sequence[str], None] = '87fd24734672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priority_levels', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priority_levels', sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
