"""sync with models

Revision ID: ee73da718dd3
Revises: 
Create Date: 2025-11-30 03:41:58.684154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee73da718dd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # --- 1. РУЧНАЯ ВСТАВКА: CASCADE DELETE ДЛЯ MEMBERS ---
    # Alembic часто пропускает обновление FK, делаем это явно.
    # Удаляем старый внешний ключ (стандартное имя в Postgres)
    try:
        op.drop_constraint('project_members_project_id_fkey', 'project_members', type_='foreignkey')
    except Exception:
        # Если имя ключа другое или его нет, не падаем
        pass

    # Создаем новый ключ с правилом удаления CASCADE
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # -----------------------------------------------------

    # ### commands auto generated by Alembic ###

    # 2. CASCADE DELETE ДЛЯ TOKENS (Это Alembic сгенерировал сам)
    op.alter_column('project_invitations_tokens', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('project_invitations_tokens_project_id_fkey'), 'project_invitations_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'project_invitations_tokens', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # 3. ОСТАЛЬНЫЕ ИЗМЕНЕНИЯ (Синхронизация типов и nullable)
    op.drop_constraint(op.f('project_members_project_id_user_id_key'), 'project_members', type_='unique')
    op.drop_constraint(op.f('project_purposes_name_key'), 'project_purposes', type_='unique')
    op.create_index(op.f('ix_project_purposes_name'), 'project_purposes', ['name'], unique=True)

    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=250),
               existing_nullable=False)

    op.drop_constraint(op.f('uix_user_project_name'), 'projects', type_='unique')
    op.drop_constraint(op.f('uq_project_name_user'), 'projects', type_='unique')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])

    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)

    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'inactive'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # --- ОТКАТ РУЧНОЙ ВСТАВКИ ---
    # Удаляем каскадный ключ
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    # Возвращаем обычный ключ (без cascade)
    op.create_foreign_key('project_members_project_id_fkey', 'project_members', 'projects', ['project_id'], ['id'])
    # ----------------------------

    # ### commands auto generated by Alembic ###
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'inactive'::character varying"))
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_project_name_user'), 'projects', ['name', 'created_by'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_user_project_name'), 'projects', ['name', 'created_by'], postgresql_nulls_not_distinct=False)

    op.alter_column('projects', 'name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_index(op.f('ix_project_purposes_name'), table_name='project_purposes')
    op.create_unique_constraint(op.f('project_purposes_name_key'), 'project_purposes', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('project_members_project_id_user_id_key'), 'project_members', ['project_id', 'user_id'], postgresql_nulls_not_distinct=False)

    op.drop_constraint(None, 'project_invitations_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('project_invitations_tokens_project_id_fkey'), 'project_invitations_tokens', 'projects', ['project_id'], ['id'])
    op.alter_column('project_invitations_tokens', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###