name: DAST - ZAP Baseline

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL задеплоенного приложения"
        required: true
        default: "https://diploma-thesis.onrender.com/docs"
        type: string

permissions:
  contents: read

jobs:
  zap-baseline:
    name: Scan deployed application
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: ${{ inputs.target_url }}
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-baseline-report
